# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geolocation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11geolocation.proto\x12\x0bgeolocation\x1a\x1fgoogle/protobuf/timestamp.proto"|\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x31\n\rcreation_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"4\n\x10LocationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2c\n\x12GeoLocationService\x12M\n\x0cSendLocation\x12\x1c.geolocation.LocationMessage\x1a\x1d.geolocation.LocationResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "geolocation_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LOCATIONMESSAGE"]._serialized_start = 67
    _globals["_LOCATIONMESSAGE"]._serialized_end = 191
    _globals["_LOCATIONRESPONSE"]._serialized_start = 193
    _globals["_LOCATIONRESPONSE"]._serialized_end = 245
    _globals["_GEOLOCATIONSERVICE"]._serialized_start = 247
    _globals["_GEOLOCATIONSERVICE"]._serialized_end = 346
# @@protoc_insertion_point(module_scope)
