---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation-server
  template:
    metadata:
      labels:
        app: geolocation-server
    spec:
      containers:
      - name: geolocation-server
        image: cadmus86/udaconnect:ms-location-ingester
        ports:
        - containerPort: 50051
        imagePullPolicy: Always
        env:
        - name: GRPC_SERVER_PORT
          value: "50051"
        - name: KAFKA_TOPIC
          value: geolocation_topic
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: LOG_LEVEL
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-server
spec:
  selector:
    app: geolocation-server
  ports:
    - port: 50051
      targetPort: 50051
  type: ClusterIP
