apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-location-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-location-processor
  template:
    metadata:
      labels:
        app: ms-location-processor
    spec:
      containers:
      - name: ms-location-processor
        image: cadmus86/udaconnect:ms-location-processor
        env:
        - name: KAFKA_TOPIC
          value: geolocation_topic
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: LOG_LEVEL
          value: "INFO"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        imagePullPolicy: Always
